### PR TITLE
Merge report-system to master 

### PR DESCRIPTION
**Pull request by ttxking**
* This merge include:
 - test files of the report system
 - flake8 file
 - reformatted file
* This merge is to increase codecov% and for Travis CI to run the test

### CODE REVIEW

**Review by bemyXmas — APPROVED** [review]
I pulled and tested it, It's working fine GJ!

**Comment by ttxking** [comment]
> I pulled and tested it, It's working fine GJ!

Thank you~

**Review by Kuea666 — APPROVED** [review]
I pulled to test and it didn't find any problems.
GUD!

**Comment by ttxking** [comment]
> I pulled to test and it didn't find any problems.
> GUD!

Ok, Thank you 😘

**Review by nicenicegame — APPROVED** [review]
Good to use flake8 to check the coding style, didn’t found any problems!

**Comment by ttxking** [comment]
> Good to use flake8 to check the coding style didn’t found any problems!

ok will merge now

**Pull request merged**
